server:
  servlet:
    context-path: /cliente-endereco/api

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cliente_endereco}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true